package dao;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.EnumerationValue;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class EnumerationValueRepository extends RepositoryBase<EnumerationValue> implements IEnumerationValueRepository {

	protected PreparedStatement withNameSt;
	protected PreparedStatement withIntKeySt;
	protected PreparedStatement withStringKeySt;

	public EnumerationValueRepository(Connection connection,
									  IMapResultSetToEntity<EnumerationValue> mapper,
									  IUnitOfWork uow) {
		super(connection, mapper, uow);
		try {
			withNameSt = connection.prepareStatement("SELECT * FROM enumeration WHERE name = ?");
			withIntKeySt = connection.prepareStatement("SELECT * FROM enumeration WHERE intKey = ? and name = ?");
			withStringKeySt = connection.prepareStatement("SELECT * FROM enumeration WHERE stringKey = ? and name = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public void setUpdateQuery(EnumerationValue e) throws SQLException {
		update.setInt(1, e.getIntKey());
		update.setString(2, e.getStringKey());
		update.setString(3, e.getValue());
		update.setString(4, e.getName());
		update.setInt(5, e.getId());
	}

	public void setInsertQuery(EnumerationValue e) throws SQLException {
		insert.setInt(1, e.getIntKey());
		insert.setString(2, e.getStringKey());
		insert.setString(3, e.getValue());
		insert.setString(4, e.getName());
	}

	@Override
	protected String tableName() {
		return "enumeration";
	}

	protected String createTableSql() {
		return "CREATE TABLE enumeration("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "stringKey VARCHAR(20)," + "intKey bigint," + "value VARCHAR(50)," + "name VARCHAR(50)"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO enumeration(intKey, stringKey, value, name) VALUES (?,?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE enumeration SET intKey = ?, stringKey = ?, value = ?, name = ? WHERE id = ?";
	}

	public List<EnumerationValue> withName(String name) {
		try {
			withNameSt.setString(1, name);
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return getList(withNameSt);
	}

	public List<EnumerationValue> withIntKey(int key, String name) {
		try {
			withIntKeySt.setInt(1, key);
			withIntKeySt.setString(2, name);
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return getList(withIntKeySt);
	}

	public List<EnumerationValue> withStringKey(String key, String name) {
		try {
			withStringKeySt.setString(1, key);
			withStringKeySt.setString(2, name);
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return getList(withStringKeySt);
	}
}
