package dao;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.GroupsRoles;

import java.sql.Connection;
import java.sql.SQLException;


public class GroupsRolesRepository extends RepositoryBase<GroupsRoles> implements IGroupRolesRepository{

	public GroupsRolesRepository(Connection connection,
								 IMapResultSetToEntity<GroupsRoles> mapper,
								 IUnitOfWork uow) {

		super(connection,mapper, uow);
	}

	@Override
	protected String tableName() {
		return "groups_roles";
	}

	protected String createTableSql() {
		return "CREATE TABLE groups_roles("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "roleId int," + "groupId int"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO groups_roles(roleId, groupId) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE groups_roles SET roleId = ?, groupId = ? WHERE id = ?";
	}

	public void setUpdateQuery(GroupsRoles gr) throws SQLException {
		update.setInt(1, gr.getRoleId());
		update.setInt(2, gr.getGroupId());
		update.setInt(3, gr.getId());
	}

	public void setInsertQuery(GroupsRoles gr) throws SQLException {
		insert.setInt(1, gr.getRoleId());
		insert.setInt(2, gr.getGroupId());
	}
}
