package dao;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.Groups;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class GroupsRepository extends RepositoryBase<Groups> implements IGroupsRepository {

	protected PreparedStatement withNameSt;

	public GroupsRepository(Connection connection,
							IMapResultSetToEntity<Groups> mapper,
							IUnitOfWork uow) {

		super(connection, mapper, uow);
		try {
			withNameSt = connection.prepareStatement("SELECT * FROM groups WHERE name = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	protected String tableName() {
		return "groups";
	}

	protected String createTableSql() {
		return "CREATE TABLE groups("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(30)"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO groups(name) VALUES (?)";
	}

	protected String updateSql() {
		return "UPDATE groups SET name = ? WHERE id = ?";
	}

	public void setUpdateQuery(Groups g) throws SQLException {
		update.setString(1, g.getName());
		update.setInt(2, g.getId());
	}

	public void setInsertQuery(Groups g) throws SQLException {
		insert.setString(1, g.getName());
	}

	public List<Groups> withName(String name) {
		try {
			withNameSt.setString(1, name);
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return getList(withNameSt);
	}
}
