package dao;

import dao.mappers.IMapResultSetToEntity;
import dao.uow.IUnitOfWork;
import domain.RolesPermissions;

import java.sql.Connection;
import java.sql.SQLException;

public class RolesPermissionsRepository extends RepositoryBase<RolesPermissions> implements IRolesPermissionsRepository{

	public RolesPermissionsRepository(Connection connection,
									  IMapResultSetToEntity<RolesPermissions> mapper,
									  IUnitOfWork uow) {

		super(connection,mapper, uow);
	}

	@Override
	protected String tableName() {
		return "roles_permissions";
	}

	protected String createTableSql() {
		return "CREATE TABLE roles_permissions("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "permName VARCHAR(30)," + "permType int"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO roles_permissions(permName, permType) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE roles_permissions SET permName = ?, permType = ? WHERE id = ?";
	}

	public void setUpdateQuery(RolesPermissions rp) throws SQLException {
		update.setString(1, rp.getPermName());
		update.setInt(2, rp.getPermType());
		update.setInt(3, rp.getId());
	}

	public void setInsertQuery(RolesPermissions rp) throws SQLException {
		insert.setString(1, rp.getPermName());
		insert.setInt(2, rp.getPermType());
	}
}
